// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcControleJogo.Models;

namespace MvcControleJogo.Migrations
{
    [DbContext(typeof(MvcClienteContext))]
    [Migration("20181122094800_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("MvcControleJogo.Models.Categoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescricaoCategoria");

                    b.Property<string>("NomeCategoria");

                    b.HasKey("ID");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("MvcControleJogo.Models.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnoNasc");

                    b.Property<string>("Celular");

                    b.Property<string>("Cpf");

                    b.Property<string>("NomeCliente");

                    b.Property<string>("Rg");

                    b.HasKey("ID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("MvcControleJogo.Models.ClienteJogo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("NomeClienteFKID");

                    b.Property<int?>("NomeJogoFKID");

                    b.HasKey("ID");

                    b.HasIndex("NomeClienteFKID");

                    b.HasIndex("NomeJogoFKID");

                    b.ToTable("ClienteJogo");
                });

            modelBuilder.Entity("MvcControleJogo.Models.Empresa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cnpj");

                    b.Property<string>("Fundacao");

                    b.Property<string>("NomeEmpresa");

                    b.HasKey("ID");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("MvcControleJogo.Models.Jogos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnoLanc");

                    b.Property<int?>("DesenvolvedorFKID");

                    b.Property<int?>("NomeCategoriaFKID");

                    b.Property<string>("NomeJogo");

                    b.Property<int?>("NomePlataformaFKID");

                    b.HasKey("ID");

                    b.HasIndex("DesenvolvedorFKID");

                    b.HasIndex("NomeCategoriaFKID");

                    b.HasIndex("NomePlataformaFKID");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("MvcControleJogo.Models.Plataforma", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescricaoPlataforma");

                    b.Property<string>("NomePlataforma");

                    b.HasKey("ID");

                    b.ToTable("Plataforma");
                });

            modelBuilder.Entity("MvcControleJogo.Models.ClienteJogo", b =>
                {
                    b.HasOne("MvcControleJogo.Models.Cliente", "NomeClienteFK")
                        .WithMany()
                        .HasForeignKey("NomeClienteFKID");

                    b.HasOne("MvcControleJogo.Models.Jogos", "NomeJogoFK")
                        .WithMany()
                        .HasForeignKey("NomeJogoFKID");
                });

            modelBuilder.Entity("MvcControleJogo.Models.Jogos", b =>
                {
                    b.HasOne("MvcControleJogo.Models.Empresa", "DesenvolvedorFK")
                        .WithMany()
                        .HasForeignKey("DesenvolvedorFKID");

                    b.HasOne("MvcControleJogo.Models.Categoria", "NomeCategoriaFK")
                        .WithMany()
                        .HasForeignKey("NomeCategoriaFKID");

                    b.HasOne("MvcControleJogo.Models.Plataforma", "NomePlataformaFK")
                        .WithMany()
                        .HasForeignKey("NomePlataformaFKID");
                });
#pragma warning restore 612, 618
        }
    }
}
